Repository HEPData/hepdata_lib, pull requests merged in 2018-06, with the labels that each got.

#33 remove pylint temporarily
  setup.cfg
  setup.py
Labels: review

#31 Improve logic of table output file creation
  .gitignore
  hepdata_lib/__init__.py
  tests/test_rootfilereader.py
  tests/test_submission.py
  tests/test_table.py
Labels: enhancement, review

#39 first version of Dockerfile
  Dockerfile
Labels: enhancement

#42 Getting started
  .gitignore
  README.md
  examples/Getting_started.ipynb
  examples/combine_limits.ipynb
  examples/example_inputs/BprimeBToHB1000_cat0_singleH.root
  examples/example_inputs/CMS-B2G-17-009_Figure_004-a.pdf
  examples/example_inputs/Data_cat0_singleH.root
  examples/example_inputs/Figure_006-a.pdf
  examples/example_inputs/WWmerged.higgsCombineTest.Asymptotic.root
  examples/example_inputs/abstract.txt
  examples/example_inputs/effacc_signal.txt
  examples/example_inputs/mlfit_lm_1000.root
  examples/example_inputs/signalEffVsMass.pdf
  examples/reading_histograms.ipynb
  setup.py
Labels: documentation

#48 Coverage
  .travis.yml
  .travis/setup.sh
  README.md
  setup.cfg
  setup.py
Labels: enhancement

#47 install imagemagick in docker image
  Dockerfile
Labels: bug

#44 create Submission even if ImageMagick is not installed
  hepdata_lib/__init__.py
  tests/test_execute_command.py
Labels: enhancement

#49 fix SWAN link
  README.md
Labels: bug

#53 custom build hook providing more schema variables for automated conta…
  README.md
  hooks/build
Labels: documentation, enhancement

#52 New defaultdict representer
  hepdata_lib/__init__.py
  tests/test_submission.py
  tests/test_table.py
Labels: bug, compatibility
