Repository HEPData/hepdata_lib, pull requests merged in 2019-08, with the labels that each got.

#103 Patch ImageMagick policy.xml
  .travis.yml
  .travis/setup.sh
Labels: tests

#104 Add .readthedocs.yml
  .readthedocs.yml
Labels: documentation

#105 Tuple rounding
  hepdata_lib/helpers.py
  tests/test_helpers.py
Labels: enhancement
